import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './Providers'
import UserProvider from './context/UserProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="bg-zinc-900 text-white">
            <Providers>
              <UserProvider>
                {children}
              </UserProvider>
            </Providers>
        </body>
    </html>
  )
}
